export const TASKS_LOADING = 'TASKS_LOADING';
export const ADD_TASKS = 'ADD_TASKS';
export const TASKS_FAILED = 'TASKS_FAILED';

export const POST_FAVORITE = 'POST_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
