export const TASKS_LOADING = 'TASKS_LOADING';
export const ADD_TASKS = 'ADD_TASKS';
export const TASKS_FAILED = 'TASKS_FAILED';


// REWARDS
export const REWARDS_LOADING = 'REWARDS_LOADING';
export const ADD_REWARDS = 'ADD_REWARDS';
export const REWARDS_FAILED = 'REWARDS_FAILED';
// REWARDS

export const POST_FAVORITE = 'POST_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGES = 'ADD_MESSAGES';
export const POST_MESSAGE = 'POST_MESSAGE';


export const APPOINTMENTS_LOADING = 'APPOINTMENTS_LOADING';
export const ADD_APPOINTMENTS = 'ADD_APPOINTMENTS';
export const APPOINTMENTS_FAILED = 'APPOINTMENTS_FAILED';